
5.1 Shipping Addresses for October 2023 Orders

Question: Retrieve shipping addresses for orders created or completed in October 2023.

SELECT
    oh.ORDER_ID,
    orr.PARTY_ID,
    CONCAT(p.FIRST_NAME,' ',p.LAST_NAME) AS CUSTOMER_NAME,
    pa.ADDRESS1,
    pa.CITY,
    pa.STATE_PROVINCE_GEO_ID,
    pa.POSTAL_CODE,
    pa.COUNTRY_GEO_ID,
    os.STATUS_ID,
    oh.ORDER_DATE
FROM order_header oh
JOIN order_status os
    ON oh.ORDER_ID = os.ORDER_ID
JOIN order_role orr
    ON oh.ORDER_ID = orr.ORDER_ID
JOIN person p
    ON orr.PARTY_ID = p.PARTY_ID
JOIN order_contact_mech ocm
    ON oh.ORDER_ID = ocm.ORDER_ID
JOIN postal_address pa
    ON ocm.CONTACT_MECH_ID = pa.CONTACT_MECH_ID
WHERE orr.ROLE_TYPE_ID = 'PLACING_CUSTOMER'
  AND ocm.CONTACT_MECH_PURPOSE_TYPE_ID = 'SHIPPING_LOCATION'
  AND os.STATUS_ID IN ('ORDER_CREATED','ORDER_COMPLETED')
  AND os.STATUS_DATETIME >= '2023-10-01'
  AND os.STATUS_DATETIME < '2023-11-01';



5.2 Orders from New York

Question: Retrieve orders whose shipping address is in New York.

SELECT
    oh.ORDER_ID,
    CONCAT(p.FIRST_NAME,' ',p.LAST_NAME) AS CUSTOMER_NAME,
    pa.ADDRESS1,
    pa.CITY,
    pa.STATE_PROVINCE_GEO_ID,
    pa.POSTAL_CODE,
    oh.GRAND_TOTAL,
    oh.ORDER_DATE,
    os.STATUS_ID
FROM order_header oh
JOIN order_status os
    ON oh.ORDER_ID = os.ORDER_ID
JOIN order_role orr
    ON oh.ORDER_ID = orr.ORDER_ID
JOIN person p
    ON orr.PARTY_ID = p.PARTY_ID
JOIN order_contact_mech ocm
    ON oh.ORDER_ID = ocm.ORDER_ID
JOIN postal_address pa
    ON ocm.CONTACT_MECH_ID = pa.CONTACT_MECH_ID
WHERE orr.ROLE_TYPE_ID = 'PLACING_CUSTOMER'
  AND ocm.CONTACT_MECH_PURPOSE_TYPE_ID = 'SHIPPING_LOCATION'
  AND pa.STATE_PROVINCE_GEO_ID = 'NY';



5.3 Top Selling Product in New York

Question: Find the best-selling products in New York.

SELECT
    p.PRODUCT_ID,
    p.INTERNAL_NAME,
    SUM(oi.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(oi.QUANTITY * oi.UNIT_PRICE) AS REVENUE
FROM order_item oi
JOIN product p
    ON oi.PRODUCT_ID = p.PRODUCT_ID
JOIN order_header oh
    ON oi.ORDER_ID = oh.ORDER_ID
JOIN order_contact_mech ocm
    ON oh.ORDER_ID = ocm.ORDER_ID
JOIN postal_address pa
    ON ocm.CONTACT_MECH_ID = pa.CONTACT_MECH_ID
WHERE ocm.CONTACT_MECH_PURPOSE_TYPE_ID = 'SHIPPING_LOCATION'
  AND pa.STATE_PROVINCE_GEO_ID = 'NY'
GROUP BY p.PRODUCT_ID, p.INTERNAL_NAME
ORDER BY TOTAL_QUANTITY_SOLD DESC;



7.3 Facility Wise Revenue

Question: Calculate revenue generated by each facility.

SELECT
    f.FACILITY_ID,
    f.FACILITY_NAME,
    COUNT(DISTINCT oh.ORDER_ID) AS TOTAL_ORDERS,
    SUM(oh.GRAND_TOTAL) AS TOTAL_REVENUE
FROM order_header oh
JOIN order_item_ship_group oisg
    ON oh.ORDER_ID = oisg.ORDER_ID
JOIN facility f
    ON oisg.FACILITY_ID = f.FACILITY_ID
WHERE oh.STATUS_ID = 'ORDER_COMPLETED'
GROUP BY f.FACILITY_ID, f.FACILITY_NAME;




8.1 Lost and Damaged Inventory

Question: Find inventory items marked as lost or damaged.

SELECT
    ii.INVENTORY_ITEM_ID,
    ii.PRODUCT_ID,
    ii.FACILITY_ID,
    iiv.QUANTITY_ON_HAND_VAR,
    iiv.VARIANCE_REASON_ID,
    iiv.CREATED_TX_STAMP
FROM inventory_item ii
JOIN inventory_item_variance iiv
    ON ii.INVENTORY_ITEM_ID = iiv.INVENTORY_ITEM_ID
WHERE iiv.VARIANCE_REASON_ID IN ('VAR_DAMAGED','VAR_LOST');
8.3 Current Facility of Open Orders

Question: Retrieve facility information for open orders.

SELECT
    oh.ORDER_ID,
    oh.STATUS_ID,
    f.FACILITY_ID,
    f.FACILITY_NAME,
    f.FACILITY_TYPE_ID
FROM order_header oh
JOIN order_item_ship_group oisg
    ON oh.ORDER_ID = oisg.ORDER_ID
JOIN facility f
    ON oisg.FACILITY_ID = f.FACILITY_ID
WHERE oh.STATUS_ID = 'ORDER_CREATED';




8.4 Items Where ATP and QOH Differ

Question: Find inventory items where ATP and QOH do not match.

SELECT
    PRODUCT_ID,
    FACILITY_ID,
    QUANTITY_ON_HAND_TOTAL AS QOH,
    AVAILABLE_TO_PROMISE_TOTAL AS ATP,
    (QUANTITY_ON_HAND_TOTAL - AVAILABLE_TO_PROMISE_TOTAL) AS DIFFERENCE
FROM inventory_item
WHERE QUANTITY_ON_HAND_TOTAL <> AVAILABLE_TO_PROMISE_TOTAL;




8.6 Total Orders by Sales Channel

Question: Calculate orders and revenue by sales channel.

SELECT
    SALES_CHANNEL_ENUM_ID AS SALES_CHANNEL,
    COUNT(*) AS TOTAL_ORDERS,
    SUM(GRAND_TOTAL) AS TOTAL_REVENUE
FROM order_header
GROUP BY SALES_CHANNEL_ENUM_ID;