
5.1 Shipping Addresses for October 2023 Orders

Question: Retrieve shipping addresses for orders created or completed in October 2023.

SELECT
    oh.ORDER_ID,
    orr.PARTY_ID,
    CONCAT(p.FIRST_NAME,' ',p.LAST_NAME) AS CUSTOMER_NAME,
    pa.ADDRESS1,
    pa.CITY,
    pa.STATE_PROVINCE_GEO_ID,
    pa.POSTAL_CODE,
    pa.COUNTRY_GEO_ID,
    os.STATUS_ID,
    oh.ORDER_DATE
FROM order_header oh
JOIN order_status os
    ON oh.ORDER_ID = os.ORDER_ID
JOIN order_role orr
    ON oh.ORDER_ID = orr.ORDER_ID
JOIN person p
    ON orr.PARTY_ID = p.PARTY_ID
JOIN order_contact_mech ocm
    ON oh.ORDER_ID = ocm.ORDER_ID
JOIN postal_address pa
    ON ocm.CONTACT_MECH_ID = pa.CONTACT_MECH_ID
WHERE orr.ROLE_TYPE_ID = 'PLACING_CUSTOMER'
  AND ocm.CONTACT_MECH_PURPOSE_TYPE_ID = 'SHIPPING_LOCATION'
  AND os.STATUS_ID IN ('ORDER_CREATED','ORDER_COMPLETED')
  AND os.STATUS_DATETIME >= '2023-10-01'
  AND os.STATUS_DATETIME < '2023-11-01';



5.2 Orders from New York

Question: Retrieve orders whose shipping address is in New York.

SELECT
    oh.ORDER_ID,
    CONCAT(p.FIRST_NAME,' ',p.LAST_NAME) AS CUSTOMER_NAME,
    pa.ADDRESS1,
    pa.CITY,
    pa.STATE_PROVINCE_GEO_ID,
    pa.POSTAL_CODE,
    oh.GRAND_TOTAL,
    oh.ORDER_DATE,
    os.STATUS_ID
FROM order_header oh
JOIN order_status os
    ON oh.ORDER_ID = os.ORDER_ID
JOIN order_role orr
    ON oh.ORDER_ID = orr.ORDER_ID
JOIN person p
    ON orr.PARTY_ID = p.PARTY_ID
JOIN order_contact_mech ocm
    ON oh.ORDER_ID = ocm.ORDER_ID
JOIN postal_address pa
    ON ocm.CONTACT_MECH_ID = pa.CONTACT_MECH_ID
WHERE orr.ROLE_TYPE_ID = 'PLACING_CUSTOMER'
  AND ocm.CONTACT_MECH_PURPOSE_TYPE_ID = 'SHIPPING_LOCATION'
  AND pa.STATE_PROVINCE_GEO_ID = 'NY';



5.3 Top Selling Product in New York

Question: Find the best-selling products in New York.

SELECT
    p.PRODUCT_ID,
    p.INTERNAL_NAME,
    SUM(oi.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(oi.QUANTITY * oi.UNIT_PRICE) AS REVENUE
FROM order_item oi
JOIN product p
    ON oi.PRODUCT_ID = p.PRODUCT_ID
JOIN order_header oh
    ON oi.ORDER_ID = oh.ORDER_ID
JOIN order_contact_mech ocm
    ON oh.ORDER_ID = ocm.ORDER_ID
JOIN postal_address pa
    ON ocm.CONTACT_MECH_ID = pa.CONTACT_MECH_ID
WHERE ocm.CONTACT_MECH_PURPOSE_TYPE_ID = 'SHIPPING_LOCATION'
  AND pa.STATE_PROVINCE_GEO_ID = 'NY'
GROUP BY p.PRODUCT_ID, p.INTERNAL_NAME
ORDER BY TOTAL_QUANTITY_SOLD DESC;



7.3 Facility Wise Revenue

Question: Calculate revenue generated by each facility.

select 
    f.facility_id as facility_id,
    f.facility_name as facility_name,
    count(distinct oh.order_id) as total_orders,
    sum(oh.grand_total) as total_revenue,
    concat(min(oh.entry_date), ' to ', max(oh.entry_date)) as date_range
from order_header oh
join order_item_ship_group oisg 
    on oh.order_id = oisg.order_id and oh.ENTRY_DATE >= '2020-01-01 00:00:00' and
oh.ENTRY_DATE <= '2020-01-31 00:00:00' and oh.status_id = 'ORDER_COMPLETED'
join facility f 
    on oisg.facility_id = f.facility_id 
group by f.facility_id, f.facility_name;



8.1 Lost and Damaged Inventory

Question: Find inventory items marked as lost or damaged.

SELECT ii.INVENTORY_ITEM_ID,
ii.PRODUCT_ID,
ii.FACILITY_ID,
sum(iiv.Quantity_On_Hand_Var) as QUANTITY_LOST_OR_DAMAGED,
iiv.reason_enum_id as REASON_CODE,
iiv.created_tx_stamp AS TRANSACTION_DATE
from inventory_item ii 
join inventory_item_variance iiv on ii.INVENTORY_ITEM_ID = iiv.INVENTORY_ITEM_ID and iiv.reason_enum_id in ("VAR_DAMAGED", "VAR_STOLEN", "VAR_LOST")
group by ii.inventory_item_id , iiv.reason_enum_id

Question: Retrieve facility information for open orders.

SELECT
    oh.ORDER_ID,
    oh.STATUS_ID,
    f.FACILITY_ID,
    f.FACILITY_NAME,
    f.FACILITY_TYPE_ID
FROM order_header oh
JOIN order_item_ship_group oisg
    ON oh.ORDER_ID = oisg.ORDER_ID
JOIN facility f
    ON oisg.FACILITY_ID = f.FACILITY_ID
WHERE oh.STATUS_ID = 'ORDER_CREATED';

8.3 

select oh.order_id,
      oh.status_id ,
      oisp.facility_id,
      f.facility_name,
      f.facility_type_id
      
from order_header oh 
JOIN order_item_ship_group oisp on oh.order_id= oisp.order_id 
join facility f on oisp.facility_id = f.facility_id 
where  oh.status_id not in ('ORDER_COMPLETED','ORDER_CANCELLED');


8.4 Items Where ATP and QOH Differ

Question: Find inventory items where ATP and QOH do not match.

select product_id , 
       facility_id, 
       quantity_on_hand_total,
       available_to_promise_total , 
       (quantity_on_hand_total - available_to_promise_total) as diff
from inventory_item  ;




8.6 Total Orders by Sales Channel

Question: Calculate orders and revenue by sales channel.

SELECT
    SALES_CHANNEL_ENUM_ID AS SALES_CHANNEL,
    COUNT(*) AS TOTAL_ORDERS,
    SUM(GRAND_TOTAL) AS TOTAL_REVENUE
FROM order_header
GROUP BY SALES_CHANNEL_ENUM_ID;
